package exemple;

import stateMachine.*;
/**
Generated By SCXMLToJava class
**/
public class GStateMachine extends AbstractStateMachine{
public GStateMachine(){
super();
super.stateList.add( new State().setId("standby").setIsInit(false).addTransition(new Transition().setTo(new State("opening")).addTriggerEvent("someone").addTriggeredEvent(new Event("open").addCallable(new EventSender("open", this,0)))));
super.stateList.add( new State().setId("opening").setIsInit(false).addTransition(new Transition().setTo(new State("waiting")).addTriggerEvent("opened")));
super.stateList.add( new State().setId("waiting").setIsInit(false).addTransition(new Transition().setTo(new State("closing")).addTriggerEvent("endWaiting").addTriggeredEvent(new Event("close").addCallable(new EventSender("close", this,0)))).addOnEntry(new Event("endWaiting").addCallable(new EventSender("endWaiting", this,1000))));
super.stateList.add( new State().setId("closing").setIsInit(false).addTransition(new Transition().setTo(new State("standby")).addTriggerEvent("closed")));
super.linkStates();
super.init();
}}