package stateMachine;
/**
Generated By SCXMLToJava class
**/
public class GStateMachine extends AbstractStateMachine{
public GStateMachine(){
super();
super.stateList.add( new State().setId("State_1").setIsInit(false).addTransition(new Transition().setTo(new State("State_2")).addTriggerEvent("Transition_9")));
super.stateList.add( new State().setId("State_2").setIsInit(false).addOnEntry(new Event("aezge").addCallable(new EventSender("aezge", this))).addOnExit(new Event("zerzer").addCallable(new EventSender("zerzer", this))));
super.stateList.add( new State().setId("State_4").setIsInit(false));
super.linkStates();
super.init();
}}